name: BossPlugin
version: 3.21
api: 3.22.1
author: HmmHmmmmm
main: hmmhmmmm\boss\Boss
website: https://github.com/raditya743/BossPlugin
depend:
- Slapper
- PureEntitiesX

permissions:
  bossplugin:
    default: false
    children:
      bossplugin.command:
        default: false
        children:
          bossplugin.command.boss:
            default: op
